Update cicd

diff --git a/cicd b/cicd
--- a/cicd
+++ b/cicd
@@ -1,160 +1,87 @@
+name: ADL Deploy Artifacts
+on:
+  repository_dispatch:
+    types:
+      - adl-aws-deploy
+jobs:
+  adl-aws-deploy:
+    env:
+      event_repo_name: ${{ github.event.client_payload.name }}
+      cicd_version: ${{ github.event.client_payload.cicd_version }}
+      event_repo_branch: ${{ github.event.client_payload.branch }}
+      calling_repo_name: ${{ github.event.repository.full_name }}
+      dispatch_repo_name: ${{ 'adl-awsdeploy-cicd' }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: Log Environment Variables
+        run: |
+          echo "This is the Repo to deploy: ${event_repo_name}"
+          echo "This is the stable repo release version to deploy: ${cicd_version}"
+          echo "This is the Repo that made the request: ${calling_repo_name}"
+          echo "This is the Version Of CICD being used: ${calling_repo_name}-${cicd_version}"
 
-module "adl_globals" {
-  source = "../../modules/module-adl-global"
+      - name: Check Calling Repository
+        run: |
+          calling_repo_base_name=${calling_repo_name##*/}
+          if [[ ${calling_repo_base_name} != ${dispatch_repo_name} ]]
+          then
+            echo "adl-aws-deploy called from invalid origin, fail and exit"
+            exit 1
+          fi
+      - name: Get Requesting Repository
+        env:
+          github_user: ${{ secrets.GH_USER_NAME }}
+          github_token: ${{ secrets.GH_CLONE_REPO }}
+        run: |
+          versioned_calling_repo_base_name=${calling_repo_name}-${cicd_version}
+          echo "This is versioned_calling_repo_base_name: ${versioned_calling_repo_base_name}"
+          git clone --single-branch --depth=1 --branch=${cicd_version} https://${github_user}:${github_token}@github.com/${calling_repo_name}.git ${versioned_calling_repo_base_name}
+          git clone --single-branch --depth=1 --branch=${event_repo_branch} https://${github_user}:${github_token}@github.com/${event_repo_name}.git
+      - name: Increment Calling Repo Version
+        run: |
+          versioned_calling_repo_base_name=${calling_repo_name}-${cicd_version}
+          event_repo_base_name=${event_repo_name##*/}
+          source ${versioned_calling_repo_base_name}/scripts/.mdshrc
+          mdsh_init ${event_repo_branch} local adl ${event_repo_base_name} localhost
+          git config --global user.email "david.madison@alight.com"
+          git config --global user.name "David Madison"
+          if [[ "${mdsh_env}" = "dev" ]]
+          then
+            bump_version patch ${event_repo_base_name}
+            git -C ${event_repo_base_name} add .version
+            git -C ${event_repo_base_name} commit -m "Increments Version"
+            git -C ${event_repo_base_name} push
+          fi
+          new_git_tag=$(version ${event_repo_base_name})
+          gtag_version ${event_repo_base_name} ${mdsh_env} ${new_git_tag} "CICD Pipeline Merge To ${event_repo_branch}"
+      - name: ADL Set Environment Credentials
+        id: adl-set-env-creds
+        run: |
+          versioned_calling_repo_base_name=${calling_repo_name}-${cicd_version}
+          source ${versioned_calling_repo_base_name}/config/.cicdrc ${event_repo_branch}
+          echo "aws_access_key_id_name=ADL_${credential_env}_ACCESS_KEY" >> $GITHUB_OUTPUT
+          echo "aws_secret_access_key_name=ADL_${credential_env}_SECRET_KEY" >> $GITHUB_OUTPUT
 
-  application     = var.application
-  service         = var.service
-  environment     = var.environment
-  additional_tags = merge(var.tags, { "dataproduct" = var.service })
-}
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v1-node16
+        env:
+          AWS_ACCESS_KEY_ID_NAME: ${{ steps.adl-set-env-creds.outputs.aws_access_key_id_name }}
+          AWS_SECRET_ACCESS_KEY_NAME: ${{ steps.adl-set-env-creds.outputs.aws_secret_access_key_name }}
+        with:
+          aws-access-key-id: ${{ secrets[env.AWS_ACCESS_KEY_ID_NAME] }}
+          aws-secret-access-key: ${{ secrets[env.AWS_SECRET_ACCESS_KEY_NAME] }}
+          aws-region: us-east-1
+      - name: Install Dependencies
+        run: |
+          versioned_calling_repo_base_name=${calling_repo_name}-${cicd_version}
+          echo "Installing dependencies from ${versioned_calling_repo_base_name}/requirements.txt"
+          pip install -r ${versioned_calling_repo_base_name}/requirements.txt
+      - name: Run CICD Pipeline
+        run: |
+          versioned_calling_repo_base_name=${calling_repo_name}-${cicd_version}
+          export BUILD_NUMBER=${{ github.run_number }}
+          event_repo_base_name=${event_repo_name##*/}
+          export PYTHONPATH=${PWD}/${versioned_calling_repo_base_name}/src:${PWD}/${event_repo_base_name}/src/:$PYTHONPATH
+          source ${versioned_calling_repo_base_name}/scripts/.mdshrc
+          adl_repo_cicd ${event_repo_branch} ${event_repo_base_name} ${versioned_calling_repo_base_name}
 
-locals {
-  layer_names = {
-    codepipeline     = "codepipeline"
-  }
-}
-
-
-
-#####################create s3 bucket#########################
-# module "s3_bucket_codepipeline" {
-#   source = "../../modules/module-adl-s3"
-#   application = var.application
-#   service     = "${var.service}-${local.layer_names.codepipeline}"
-#   environment = module.adl_globals.environment
-#   tags        = module.adl_globals.tags
-#   enable_versioning = true
-#   #kms_key_arn     = "arn:aws:kms:us-east-1:056994788717:key/6216a2ac-e111-4504-8b90-1aad693cd66f"
-# }
-
-data "aws_iam_role" "example" {
-  name = "TerraformOperations"
-}
-
-###################################################
-## Create CodePipeline for buildspec              ###
-###################################################
-
-resource "aws_s3_object" "default_folders" {
-  bucket = var.source_s3_bucket
-  key    = "cicd/codedeploy/${var.service}/${var.repo_name}/"
-}
-
-# Create the codepipeline for taking code from S3 or codecommit and build/deploying to corresponding module 
-resource "aws_codepipeline" "codepipeline" {
-  name = format("%s-%s-%s-codepipeline", var.application,module.adl_globals.environment, var.codepipelinename)
-  role_arn = aws_iam_role.codepipeline_role.arn
-  #role_arn = data.aws_iam_role.example.arn
-  artifact_store {
-    #location = module.s3_bucket_codepipeline.bucket_name
-    location = var.source_s3_bucket
-    type     = "S3"
-    encryption_key {
-      id = module.adl_globals.kms_cmk_arn
-      type = "KMS"
-    }
-  }
-  stage {
-
-      name = "Source"
-
-      action {
-        name     = "Source"
-        category = "Source"
-        owner    = "AWS"
-        provider = "S3"
-        version  = "1"
-
-        output_artifacts = ["SourceArtifact"]
-
-        configuration = {
-          S3Bucket             = var.source_s3_bucket
-          // build_code = deploy.zip
-          S3ObjectKey          = format("cicd/codedeploy/%s/%s/%s", var.service,var.repo_name,var.build_code)
-          PollForSourceChanges = false
-        }
-      }
-
-  }
-  stage {
-      name = "Deploy"
-      action {
-        name = "Deploy"
-        category        = "Deploy"
-        owner           = "AWS"
-        provider        = "CodeDeploy"
-        input_artifacts = ["SourceArtifact"]
-        version         = "1"
-
-        configuration = {
-          ApplicationName     = aws_codedeploy_app.codedeploy.name #format("%s-%s-%s-ec2deployment", var.application,module.adl_globals.environment,var.service)
-          DeploymentGroupName = aws_codedeploy_deployment_group.codedeploy_group.deployment_group_name
-        }
-      }
-  }  
-
-  # stage {
-  #   name = "Archive"
-
-  #   action {
-  #     name = "Archive"
-  #     category        = "Deploy"
-  #     owner           = "AWS"
-  #     provider        = "S3" 
-  #     input_artifacts = ["SourceArtifact"]
-  #     version         = "1"
-
-  #     configuration = {
-  #       "ObjectKey" = format("%s/%s-%s.zip", "archive",var.build_code,local.timestamp_sanitized)
-  #       "BucketName" = var.pipeline_bucket_name
-  #       "Extract" = "false"
-  #     }
-  #   }
-  # }
-
-
-  tags = module.adl_globals.tags
-}
-
-########### Code Deploy #########
-resource "aws_codedeploy_app" "codedeploy" {
-  name = format("%s-%s-%s-ec2deploymentapp", var.application,module.adl_globals.environment,var.codepipelinename)
-}
-
-
-resource "aws_codedeploy_deployment_group" "codedeploy_group" {  
-  app_name              = aws_codedeploy_app.codedeploy.name
-  deployment_group_name = format("%s-%s-%s-ec2deploymentgroup", var.application,module.adl_globals.environment,var.codepipelinename) 
-  service_role_arn      = aws_iam_role.cp_codedeploy_role.arn
-  deployment_config_name = aws_codedeploy_deployment_config.codedeploy_config.id
-
-  dynamic "ec2_tag_set" {
-    for_each = var.ec2_filter_tags
-    content {
-      dynamic "ec2_tag_filter" {
-        for_each = ec2_tag_set.value
-        content {
-          key   = ec2_tag_filter.value.key
-          type  = ec2_tag_filter.value.type
-          value = ec2_tag_filter.value.value
-
-        }
-      }
-    }
-    
-  }
-
-  auto_rollback_configuration {
-    enabled = true
-    events  = ["DEPLOYMENT_FAILURE"]
-  }
-
-}
-
-resource "aws_codedeploy_deployment_config" "codedeploy_config" {
-  deployment_config_name = format("%s-%s-%s-ec2deploymentconfig", var.application,module.adl_globals.environment,var.codepipelinename)
-  minimum_healthy_hosts {
-    type  = "HOST_COUNT"
-    value = 0
-  }
-}
